### ISSUE TITLE
The layout breaks for certain exact window sizes

### ISSUE THREAD

**Issue by borekl** [axyz/perfect-layout#3]
I have found that for some particular window sizes the layout completely breaks up. This happens even with the demo in Codepen, just slowly resize the window by grabbing it's right edge and you will notice that sometimes the gallery flickers... go very slowly over that size and you will find that exact pixel size where this happens.

**Comment by axyz** [comment]
I'm not able to reproduce on my platform. 
However it is probably something related with scrollbar-size and pixel rounding, having some padding should reduce those issues, but it's hard to know in advance what is going to happen with platform specific scrollbar sizes.

What browser and what OS are you using?

**Comment by borekl** [comment]
I have tried this on Windows 7 in Firefox 40.0.3 and Chrome 45.0.

I was playing with the gallery again today and I don't think this is problem with your code; I haven't been able to create gallery that would be "pre-broken" (ie. be broken right after the initial load). It seems to me as if some resize events don't get triggered. I tried to throttle the resize handler so there's a limit how often it's called—and it doesn't help at all (even when throttled to 1 call per second).

Anyway, can you try [this](https://voyager.lupomesky.cz/gallery-test.html) test gallery? It seems it triggers the problem way more often than the codepen demo.

Here's how the demo looks when it breaks: [broken-perfectlayout](https://cloud.githubusercontent.com/assets/9165897/9976902/412d20ec-5ef3-11e5-9ca5-c2c3b42dcae1.jpg)

**Comment by axyz** [comment]
on linux I can see some flickers due to the throttling, but I cannot stop on a broken layout.

It is quite difficult to recognize the correct elements' width crossbrowser with pixel perfect precision (above all when we have percent width relative to the screen width).

This is the main reason why my jquery implementation is only an example and suggestion on how perfectLayout may be used (as well as the fact that I'm sure that the DOM operations may be optimized).

My advice for you is to try to play a bit with your `#gallery` padding as well as eventually subtracting some pixels from your `$(this.width)` it is probably a rounding problem of 1 or 2 pixels...

I'd really hope that with the contribution of some "cross-browser expert" I can eventually release a stable jQuery plugin in the future.

**Comment by borekl** [comment]
Subtracting just one pixel from $(this).width seems to completely cure the problem. Maybe this is some odd interaction with scaling due to me using HiDPI monitor.

I think you can close this issue.
